version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: crawler
      POSTGRES_PASSWORD: crawlerpass
      POSTGRES_DB: ski_crawler
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  crawler:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://crawler:crawlerpass@db:5432/ski_crawler
    volumes:
      - ./src:/app/src
    command: ["python", "src/main.py"]

volumes:
  db_data:
